### ISSUE TITLE
Questions about integration with Evmos

### ISSUE THREAD

**Issue by adust09** [strangelove-ventures/poa#131]
Hi team!
I'm looking into how to integrate poa into the [evmos](https://docs.evmos.org/).
Are you aware of any projects already integrating with evmos?

**Comment by Reecepbcups** [comment]
@adust09 This just slots in on top of the native staking module. This should work on evmos, but assume you won't be able to execute it from an EVM account due to the new account types. Only native evmos1 cosmos addresses would be usable as admins

**Comment by adust09** [comment]
Make sense! Thanks a lot!
