### ISSUE TITLE
jailed validators (from downtime) attempt to jail every block

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/poa#163]
Built into https://github.com/strangelove-ventures/poa/pull/160, when a validator is jailed the logic continues to try and set jailed state.

There does not seem to be a technical issue with it, but jailing a validator every block for an entire unbonding period is no bueno

## Solutions
- Fix the issue so there is only a single 1 off jail event (ideal). Probably some key / power index to set to make it happy
- Instant unbond jailed validators (and removal) rather than re-jailing

**Comment by alexanderbez** [comment]
@Reecepbcups what makes it attempt to re-jail every block? Do we need to simply need to mark the validator as jailed? Or perhaps, there is an `x/staking` or `x/slashing` method we can override?

**Comment by Reecepbcups** [comment]
@alexanderbez here is where it's sort of stemming from: https://github.com/strangelove-ventures/poa/pull/160#discussion_r1565160371

Issue: x/staking panics if pulling a jailed validator from the validator set on ApplyValUpdates (staking endblock). So we have to override the validator from being jailed so that the last ApplyValUpdates can be set as they begin unbonding. We can't just delete the validator outright (DeleteLastValidatorPower) from the CometBFT updates since that would be 2x abci.ValUpdate updates (x/staking) from a single val, resulting in a panic

I think a solution here is yet another cache where:
- Block 1 x/poa: we set the val.Jailed = false, add to cache. x/staking
- Block 1 x/staking, jails the validator
- Block 2 x/poa: sees a val in the toJail cache, and deletes power / sets to jail
- Block 2 x/staking: val is really jailed

pretty much a delay of jail by h+1 rather than at h

**Comment by Reecepbcups** [comment]
Update, removing this from the upstream SDK would solve the issue. Unsure why we panic vs continuing since we iter all validators anyways. 
```
func (k Keeper) ApplyAndReturnValidatorSetUpdates(ctx context.Context) (updates []abci.ValidatorUpdate, err error) {
               ...
		if validator.Jailed {
			// panic("should never retrieve a jailed validator from the power store") // replace this line w/ continue
			continue
		}
		...
}
```

**Comment by alexanderbez** [comment]
Yup, makes sense. Good catch and patch.

**Comment by Reecepbcups** [comment]
resolved in https://github.com/strangelove-ventures/poa/pull/165
