### ISSUE TITLE
Duplicate Lint Title Workflows

### ISSUE THREAD

**Issue by joelsmith-2019** [strangelove-ventures/poa#177]
Looks like there are duplicate workflows for validating a PR's title is formatted correctly:

- https://github.com/strangelove-ventures/poa/blob/main/.github/workflows/title-format.yml#L1C1-L20
- https://github.com/strangelove-ventures/poa/blob/main/.github/workflows/chores.yml#L24-L34

**Comment by Reecepbcups** [comment]
good catch! yea the dedicated title format yml file can be deleted
