### ISSUE TITLE
setup codecov account for README badges

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/poa#205]
ref: https://github.com/strangelove-ventures/poa/pull/204

If we do not have 1, does the Developer Free tier work for us?

**Comment by Reecepbcups** [comment]
also ref: https://github.com/strangelove-ventures/tokenfactory/pull/15

**Comment by beckettsean** [comment]
I need some more context, codecov is a new offering to me. Is this an external service we sign up for? A GitHub feature I need to enable?

**Comment by Reecepbcups** [comment]
It is an external service which is signed up for: https://about.codecov.io/ . used for code coverage uploads, should be free for us due to being OSS

**Comment by beckettsean** [comment]
Codecov has been [added to our org](https://github.com/organizations/strangelove-ventures/settings/installations/53285541) and is explicitly whitelisted for `poa` and `tokenfactory` repos, and no others currenrly.
